# Generated by Django 3.0.8 on 2020-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
